name = "gendex"
main = "./dist/worker.mjs"
compatibility_date = "2023-05-23"
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-dev-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-dev-0" },
  { binding = "SATNAV", bucket_name = "satnav-dev-0" }
]
kv_namespaces = [
  { binding = "BLOCKLY", id = "208d5ac0899e4d3b82968349e5480194" }
]

[build]
command = "npm run build:debug"

# PROD!
[env.production]
account_id = "fffa4b4363a7e5250af8357087263b3a"
route = { pattern = "gendex.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-prod-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-prod-0" },
  { binding = "SATNAV", bucket_name = "satnav-prod-0" }
]
kv_namespaces = [
  { binding = "BLOCKLY", id = "4703c8565f224444bf02b46dab2a84c1" }
]

[env.production.build]
command = "npm run build"

# Staging!
[env.staging]
account_id = "fffa4b4363a7e5250af8357087263b3a"
route = { pattern = "gendex-staging.dag.haus/*", zone_id = "f2f8a5b1c557202c6e3d0ce0e98e4c8e" }
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-staging-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-staging-0" },
  { binding = "SATNAV", bucket_name = "satnav-staging-0" }
]
kv_namespaces = [
  { binding = "BLOCKLY", id = "bcabfeacc274478ebe25f7bfb21ddbaa" }
]

[env.staging.build]
command = "npm run build"

# Test!
[env.test]
workers_dev = true
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-test-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-test-0" },
  { binding = "SATNAV", bucket_name = "satnav-test-0" }
]
kv_namespaces = [
  { binding = "BLOCKLY" }
]

[env.test.vars]
DEBUG = "true"

[env.alanshaw]
workers_dev = true
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"
r2_buckets = [
  { binding = "CARPARK", bucket_name = "carpark-alanshaw-0", preview_bucket_name = "carpark-alanshaw-preview-0" },
  { binding = "DUDEWHERE", bucket_name = "dudewhere-alanshaw-0", preview_bucket_name = "dudewhere-alanshaw-preview-0" },
  { binding = "SATNAV", bucket_name = "satnav-alanshaw-0", preview_bucket_name = "satnav-alanshaw-preview-0" }
]
kv_namespaces = [
  { binding = "BLOCKLY" }
]

[env.alanshaw.vars]
DEBUG = "true"
